'use strict';

export default {
	USER_SIGNED_IN: 'USER_SIGNED_IN',

	FILE_SELECTED: 'FILE_SELECTED',
	FILE_UPLOADING_PROGRESS: 'FILE_UPLOADING_PROGRESS',

	LABELS_LOADED: 'LABELS_LOADED',
	LABEL_SELECTED_TOGGLED: 'LABEL_SELECTED_TOGGLED',

	TAGS_LOADING_STARTED: 'TAGS_LOADING_STARTED',
	TAGS_LOADING_FINISHED: 'TAGS_LOADING_FINISHED',

	USER_SIGNED_OUT: 'USER_SIGNED_OUT'
};
